### ISSUE TITLE
gelfclient==0.0.4 seems to be broken

### ISSUE THREAD

**Issue by dmitriyshashkin** [larrabee/ewn#2]
python3 -m pip install ewn
Collecting ewn
  Using cached ewn-1.0.7.tar.gz
Collecting gelfclient==0.0.4 (from ewn)
  Using cached gelfclient-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3zjgc97_/gelfclient/setup.py", line 11, in <module>
        from gelfclient import __version__
      File "/tmp/pip-build-3zjgc97_/gelfclient/gelfclient/__init__.py", line 2, in <module>
        from client import UdpClient
    ImportError: No module named 'client'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3zjgc97_/gelfclient/

When I try to install gelfclient, it installs verson 0.0.5 ithout any errors. When I explicitly ask pip to install 0.0.4 it fails and outputs the same error as above. I observe the same in python 2.7

I believe updating dependency to 0.0.5 will solve the issue

**Comment by larrabee** [comment]
Hello. 
Yep, gelfclient 0.0.4 version does not work with python 3, but 0.0.5 version does not work with python 2 on CentOS 7. ;) 
I created fork of gelfclient and published new 0.0.6 version, that compatible with python 3 and CentOS. An updated version of EWN already in PyPi, try it now.

**Comment by dmitriyshashkin** [comment]
Yay! Now it works!
